### PR TITLE
Remove HTTParty dependency and legacy Google API

### PR DESCRIPTION
**Pull request by wakproductions**
I had a depedency problem using this in my project because I'm using a newer version of HTTParty for other purposes. Bundler wouldn't let me install the gem because of the version incompatibility.

### CODE REVIEW

**Comment by gregwinn** [comment]
I will review the changes and update once finished.

**Comment by gregwinn** [comment]
I can approve this pull request pending one change (noted in your request file: spec/yahoo_spec.rb Lines: 11 & 12).

Thanks!

**Comment by wakproductions** [comment]
I updated the branch but it seems you removed the troublesome HTTParty dependency in 0.4.9. FYI, you may need to push out 0.4.9 to RubyGems.org... the line in my Gemfile not working for 0.4.9.

    gem "ystock", "~> 0.4.9"

I would also recommending using tags in Git for versioning.

**Comment by gregwinn** [comment]
```
gem "ystock", "~> 0.4.10"
```

Now live with this pull request.

**Pull request merged**
